"""add service views

Revision ID: 13219a112ec2
Revises: 1955b495814a
Create Date: 2025-12-12 11:04:49.194934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13219a112ec2'
down_revision = '1955b495814a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
