"""add photo

Revision ID: 294e5e7234f3
Revises: fcff0db06240
Create Date: 2025-12-11 18:21:46.905500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294e5e7234f3'
down_revision = 'fcff0db06240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('master_users')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('master_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name=op.f('master_users_id_user_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('master_users_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('master_users_pkey'))
    )
    op.drop_table('photos')
    # ### end Alembic commands ###
